### ISSUE TITLE
Issue with Numbering when not using jb clean

### ISSUE THREAD

**Issue by mmcky** [executablebooks/sphinx-multitoc-numbering#8] opened 2020-09-30 00:35 UTC
**Describe the bug**

When running `jupyter-book` without using `jb clean` it seems that numbering picks up where it left off after the last run. Perhaps this is picking up information from the `.doctree`?

<img width="1377" alt="Screen Shot 2020-09-30 at 10 31 58 am" src="https://user-images.githubusercontent.com/8263752/94630209-68ee4700-0308-11eb-846e-48a673dc4854.png">

**To Reproduce**

Run `jupyter-book build ./` on [lecture-python-programming.myst](https://github.com/QuantEcon/lecture-python-programming.myst) without using `jb clean ./`

**Expected behavior**

Numbering should be persistent and start at 1

**Environment**

```bash
Jupyter Book: 0.8.2
MyST-NB: 0.10.1
Sphinx Book Theme: 0.0.37
MyST-Parser: 0.12.10
Jupyter-Cache: 0.4.1
NbClient: 0.5.0
```

**Comment by AakashGfude** [comment] 2020-09-30 01:53
@mmcky not able to reproduce it yet in `test-jupyter-book` branch of `lecture-python-programming.myst`.  can you also specify the version of sphinx you are using?

**Comment by AakashGfude** [comment] 2020-09-30 05:31
The reason for this issue in the CI of `lecture-python-programming.myst` was that `quantecon-book-theme` and `sphinx-multitoc-numbering` was cloned inside `lecture-python-programming.myst` folder. So, `jb build ./` considered the files of all these repos as source files and gave them numbering randomly on the basis of which files were read first.

**Comment by AakashGfude** [comment] 2020-09-30 05:33
@mmcky once we correct this in the CI, and also verify locally that this is the only reason. Then we can probably close this issue.

**Closed as completed** 2020-09-30 07:34 UTC
Labels: bug
